    !***************************************!
    !   the global library of materials     !
    !   needed for the analysis;            !
    !                                       !
    !   this module is generated by the     !
    !   preprocessing programme             !
    !***************************************!
 
 
    include 'materials/isotropic_type_module.f90'
    include 'materials/lamina_type_module.f90'
    include 'materials/interlayer_type_module.f90'
    include 'materials/material_module.f90'
   
    module lib_mat_module
    use parameter_module
    use isotropic_type_module
    use lamina_type_module
    use interlayer_type_module
    use material_module
    
    implicit none
    save
    
    type(material), allocatable          :: lib_mat(:)
    type(isotropic_type), allocatable    :: lib_iso(:)
    type(lamina_type), allocatable       :: lib_lamina(:)
    
    contains
    
    subroutine initialize_lib_mat()
        
        integer :: i=0, nmat=0, niso=0, nlamina=0
        character(len=matnamelength) :: mname1, mname2
        character(len=mattypelength) :: mtype1, mtype2
        
        mname1='test1'
        mtype1='isotropic'
        mname2='test2'
        mtype2='lamina'
        nmat=2
        niso=1
        nlamina=1
        
        allocate(lib_mat(nmat))
        allocate(lib_iso(niso))
        allocate(lib_lamina(nlamina))
    
        do i=1, nmat
            call empty(lib_mat(i))
        end do
        
        do i=1, niso
            call empty(lib_iso(i))
        end do
        
        do i=1, nlamina
            call empty(lib_lamina(i))
        end do
        
        call update(lib_mat(1),matname=mname1,mattype=mtype1,matkey=1)
        call update(lib_mat(2),matname=mname2,mattype=mtype2,matkey=1)
        
        call update(lib_iso(1), isotropic_modulus(E=100.0_dp, nu=zero))
        
        call update(lib_lamina(1), lamina_modulus(1000.0_dp,100.0_dp,40.0_dp,50.0_dp,zero,zero))
    
    
    end subroutine initialize_lib_mat
    
    
    end module lib_mat_module