    !***************************************!
    !   the global library of nodes         !
    !   used in the analysis;               !
    !                                       !
    !   this module is generated by the     !
    !   preprocessing programme             !
    !***************************************!
    
    include 'globals/xnode_module.f90'
    
    module lib_node_module
    use parameter_module
    use xnode_module
    
    implicit none
    save
    
    type(xnode) :: lib_node(40)
    
    
    contains
    
    
    subroutine initialize_lib_node()
    
        integer :: i=0
    
        do i=1, size(lib_node)
            call empty(lib_node(i))
        end do
        
        
        !~call update(lib_node(1),key=1,x=[zero,zero],u=[zero,zero])
        !~call update(lib_node(2),key=2,x=[one,zero], u=[zero,zero])
        !~call update(lib_node(3),key=3,x=[zero,one], u=[zero,zero])
        !~call update(lib_node(4),key=4,x=[one,one],  u=[zero,zero])
        !~call update(lib_node(5),key=5,x=[zero,two], u=[zero,zero])
        !~call update(lib_node(6),key=6,x=[one,two],  u=[zero,zero])        
        
        
        !~call update(lib_node(1),key=1,x=[zero,zero,-one],u=[zero,zero,zero])
        !~call update(lib_node(2),key=2,x=[one,zero,-one],u=[zero,zero,zero])
        !~call update(lib_node(3),key=3,x=[zero,one,zero],u=[zero,zero,zero])
        !~call update(lib_node(4),key=4,x=[one,one,zero],u=[zero,zero,zero])
        !~call update(lib_node(5),key=5,x=[zero,two,one],u=[zero,zero,zero])
        !~call update(lib_node(6),key=6,x=[one,two,one],u=[zero,zero,zero])
        !~
        !~call update(lib_node(7),key=7,x=[zero,zero,-one],u=[zero,zero,zero])
        !~call update(lib_node(8),key=8,x=[one,zero,-one],u=[zero,zero,zero])
        !~call update(lib_node(9),key=9,x=[zero,one,zero],u=[zero,zero,zero])
        !~call update(lib_node(10),key=10,x=[one,one,zero],u=[zero,zero,zero])
        !~call update(lib_node(11),key=11,x=[zero,two,one],u=[zero,zero,zero])
        !~call update(lib_node(12),key=12,x=[one,two,one],u=[zero,zero,zero])


        ! create real nodes
        call update(lib_node(1),key=1,x=[zero,zero,zero],u=[zero,zero,zero])
        call update(lib_node(2),key=2,x=[half,zero,zero],u=[zero,zero,zero])
        call update(lib_node(3),key=3,x=[zero,half,zero],u=[zero,zero,zero])
        call update(lib_node(4),key=4,x=[half,half,zero],u=[zero,zero,zero])
        call update(lib_node(5),key=5,x=[zero,one,zero],u=[zero,zero,zero])
        call update(lib_node(6),key=6,x=[half,one,zero],u=[zero,zero,zero])
        
        call update(lib_node(7),key=7,x=[zero,zero,quarter],u=[zero,zero,zero])
        call update(lib_node(8),key=8,x=[half,zero,quarter],u=[zero,zero,zero])
        call update(lib_node(9),key=9,x=[zero,half,quarter],u=[zero,zero,zero])
        call update(lib_node(10),key=10,x=[half,half,quarter],u=[zero,zero,zero])
        call update(lib_node(11),key=11,x=[zero,one,quarter],u=[zero,zero,zero])
        call update(lib_node(12),key=12,x=[half,one,quarter],u=[zero,zero,zero])
        
        ! create floating nodes
        do i=13,size(lib_node)
            call update(lib_node(i),key=i,x=[zero,zero,zero],u=[zero,zero,zero])
        end do
    
    end subroutine initialize_lib_node
    
    end module lib_node_module