    !***************************************!
    !   the global library of elements      !
    !   used in the analysis;               !
    !                                       !
    !   this module is generated by the     !
    !   preprocessing programme             !
    !***************************************!
 

    include 'elements/integration_point_module.f90'
    include 'elements/toolkit_module.f90'
    include 'elements/tri_element_module.f90'
    include 'elements/quad_element_module.f90'
    include 'elements/wedge_element_module.f90'
    include 'elements/brick_element_module.f90'
    include 'elements/coh2d_element_module.f90'
    ! ... and other future element modules ...
   
    module lib_elem_module
    use parameter_module
    use tri_element_module
    use quad_element_module
    use wedge_element_module
    use brick_element_module
    use coh2d_element_module
    ! ... and other future element modules ...
    
    implicit none
    save
    
    type(tri_element),allocatable   :: lib_tri(:)
    type(quad_element),allocatable  :: lib_quad(:)
    type(wedge_element),allocatable :: lib_wedge(:)
    type(brick_element),allocatable :: lib_brick(:)
    type(coh2d_element),allocatable :: lib_coh2d(:)
    
    contains
    
    subroutine initialize_lib_elem
    
        integer :: i=0, ntri=0, nquad=0, nwedge=0, nbrick=0, ncoh2d=0
        
        
        
        !------------------------------------------------------------!
        !   the rest is problem-specific
        !   and should be generated by preprocessor
        !------------------------------------------------------------!



        
        ncoh2d=1
        
        allocate(lib_coh2d(ncoh2d))
        
        do i=1, ncoh2d
            call empty(lib_coh2d(i))
        end do
        
        call prepare(lib_coh2d(1),key=1,connec=[1,2,4,3],matkey=3)
        
        
        
        !~ntri=2
        !~nquad=1
        !nwedge=2
        !nbrick=1
    
        !~if(.not.allocated(lib_tri)) allocate(lib_tri(ntri))
        !~if(.not.allocated(lib_quad)) allocate(lib_quad(nquad))
        !if(.not.allocated(lib_wedge)) allocate(lib_wedge(nwedge))
        !if(.not.allocated(lib_brick)) allocate(lib_brick(nbrick))
        
    !~
    !~    do i=1, ntri
    !~        call empty(lib_tri(i))
    !~    end do
    !~    
    !~    do i=1, nquad
    !~        call empty(lib_quad(i))
    !~    end do
          !~do i=1, nwedge
          !~  call empty(lib_wedge(i))
          !~end do
          !~do i=1, nbrick
          !~  call empty(lib_brick(i))
          !~end do
    
    !~    
    !~    call prepare(lib_tri(1),key=1,connec=[1,2,3],matkey=1)
    !~    call prepare(lib_tri(2),key=2,connec=[2,4,3],matkey=1)
    !~    call prepare(lib_quad(1),key=3,connec=[3,4,6,5],matkey=1)
    
        !~call prepare(lib_wedge(1),key=1,connec=[1,2,3,7,8,9],matkey=2)
        !~call prepare(lib_wedge(2),key=2,connec=[2,4,3,8,10,9],matkey=2)
        !~
        !~call prepare(lib_brick(1),key=1,connec=[3,4,6,5,9,10,12,11],matkey=2,theta=90._dp)
    
    end subroutine initialize_lib_elem
      
    
    end module lib_elem_module