    !***************************************!
    !   the global library of elements      !
    !   used in the analysis;               !
    !                                       !
    !   this module is generated by the     !
    !   preprocessing programme             !
    !***************************************!
 
    include 'elements/tri_element_module.f90'
    include 'elements/quad_element_module.f90'
    include 'elements/wedge_element_module.f90'
    include 'elements/brick_element_module.f90'
    include 'elements/coh2d_element_module.f90'
    include 'elements/coh3d6_element_module.f90'
    include 'elements/coh3d8_element_module.f90'
    include 'elements/sub2d_element_module.f90'
    include 'elements/sub3d_element_module.f90'
    include 'elements/xquad_element_module.f90'
    include 'elements/xbrick_element_module.f90'
    ! ... and other future element modules ...
    
    ! include generic element type (for indexing only)
    include 'elements/element_module.f90'
    
   
    module lib_elem_module
    use parameter_module
    use element_module
    use tri_element_module
    use quad_element_module
    use wedge_element_module
    use brick_element_module
    use coh2d_element_module
    use coh3d6_element_module
    use coh3d8_element_module
    use sub2d_element_module
    use sub3d_element_module
    use xquad_element_module
    use xbrick_element_module
    ! ... and other future element modules ...
    
    implicit none
    save
    
    type(element),          allocatable :: lib_elem(:)
    
    type(tri_element),      allocatable :: lib_tri(:)
    type(quad_element),     allocatable :: lib_quad(:)
    type(wedge_element),    allocatable :: lib_wedge(:)
    type(brick_element),    allocatable :: lib_brick(:)
    type(coh2d_element),    allocatable :: lib_coh2d(:)
    type(coh3d6_element),   allocatable :: lib_coh3d6(:)
    type(coh3d8_element),   allocatable :: lib_coh3d8(:)   
    type(xquad_element),    allocatable :: lib_xquad(:)
    type(xbrick_element),   allocatable :: lib_xbrick(:)
    
    contains
    
    subroutine initialize_lib_elem
    
        integer :: i=0, nelem=0, ntri=0, nquad=0, nwedge=0, nbrick=0 &
        &          ,ncoh2d=0, ncoh3d6=0, ncoh3d8=0, nsub2d=0, nsub3d=0 &
        &          ,nxquad=0, nxbrick=0
        
        
        
        !------------------------------------------------------------!
        !   the rest is problem-specific
        !   and should be generated by preprocessor
        !------------------------------------------------------------!
        
        nxbrick=1
        
        allocate(lib_xbrick(nxbrick))
        call prepare(lib_xbrick(1),key=1,bulkmat=2,cohmat=3,theta=ninety, &
        & nodecnc=[1,2,4,3,7,8,10,9,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28],edgecnc=[1,2,3,4,5,6,7,8])
        !~call prepare(lib_xbrick(2),key=2,bulkmat=2,cohmat=3,theta=ninety, &
        !~& nodecnc=[3,4,6,5,9,10,12,11,18,17,29,30,31,32,33,34,26,25,35,36,37,38,39,40],edgecnc=[3,9,10,11,7,12,13,14])


        nelem=2
        allocate(lib_elem(nelem))
        call update(lib_elem(1),elname='xbrick',eltype='xbrick',elkey=1)
        call update(lib_elem(2),elname='xbrick',eltype='xbrick',elkey=2)
        

        !~nsub3d=3
        !~allocate(lib_sub3d(nsub3d))
        !~
        !~call prepare(lib_sub3d(1),glbcnc=[1,2,3,7,8,9],         subcnc=[1,2,3,7,8,9],       eltype='wedge', matkey=1)
        !~call prepare(lib_sub3d(2),glbcnc=[2,4,3,8,10,9],        subcnc=[2,4,3,8,10,9],      eltype='wedge', matkey=1)       
        !~call prepare(lib_sub3d(3),glbcnc=[3,4,6,5,9,10,12,11],  subcnc=[3,4,6,5,9,10,12,11],eltype='brick', matkey=1)

        !~call prepare(lib_sub3d(1),glbcnc=[1,2,3,7,8,9],         subcnc=[1,2,3,7,8,9],       eltype='coh3d6', matkey=3)
        !~call prepare(lib_sub3d(2),glbcnc=[2,4,3,8,10,9],        subcnc=[2,4,3,8,10,9],      eltype='coh3d6', matkey=3)       
        !~call prepare(lib_sub3d(3),glbcnc=[3,4,6,5,9,10,12,11],  subcnc=[3,4,6,5,9,10,12,11],eltype='coh3d8', matkey=3)


        !~nsub2d=3
        !~
        !~allocate(lib_sub2d(nsub2d))
        !~call prepare(lib_sub2d(1),glbcnc=[1,2,3],   subcnc=[1,2,3],  eltype='tri',  matkey=1)
        !~call prepare(lib_sub2d(2),glbcnc=[2,4,3],   subcnc=[2,4,3],  eltype='tri',  matkey=1)
        !~call prepare(lib_sub2d(3),glbcnc=[3,4,6,5], subcnc=[3,4,6,5],eltype='quad', matkey=1)
        
        !~call prepare(lib_sub2d(1),eltype='coh2d',matkey=3,glbcnc=[1,2,4,3],subcnc=[1,2,4,3])


!~        ncoh3d6=2
!~        ncoh3d8=1
!~        allocate(lib_coh3d6(ncoh3d6))
!~        allocate(lib_coh3d8(ncoh3d8))
!~
!~        do i=1, ncoh3d6
!~            call empty(lib_coh3d6(i))
!~        end do
!~        
!~        do i=1, ncoh3d8
!~            call empty(lib_coh3d8(i))
!~        end do
!~
!~        call prepare(lib_coh3d6(1),key=1,connec=[1,2,3,7,8,9],matkey=3)
!~        call prepare(lib_coh3d6(2),key=2,connec=[2,4,3,8,10,9],matkey=3)
!~        
!~        call prepare(lib_coh3d8(1),key=3,connec=[3,4,6,5,9,10,12,11],matkey=3)
        
        
        
        
        !~ncoh2d=1
        !~
        !~allocate(lib_coh2d(ncoh2d))
        !~
        !~do i=1, ncoh2d
        !~    call empty(lib_coh2d(i))
        !~end do
        !~
        !~call prepare(lib_coh2d(1),key=1,connec=[1,2,4,3],matkey=3)
        
        
        
        !~ntri=2
        !~nquad=1
        !nwedge=2
        !nbrick=1
    
        !~if(.not.allocated(lib_tri)) allocate(lib_tri(ntri))
        !~if(.not.allocated(lib_quad)) allocate(lib_quad(nquad))
        !if(.not.allocated(lib_wedge)) allocate(lib_wedge(nwedge))
        !if(.not.allocated(lib_brick)) allocate(lib_brick(nbrick))
        
    !~
    !~    do i=1, ntri
    !~        call empty(lib_tri(i))
    !~    end do
    !~    
    !~    do i=1, nquad
    !~        call empty(lib_quad(i))
    !~    end do
          !~do i=1, nwedge
          !~  call empty(lib_wedge(i))
          !~end do
          !~do i=1, nbrick
          !~  call empty(lib_brick(i))
          !~end do
    
    !~    
    !~    call prepare(lib_tri(1),key=1,connec=[1,2,3],matkey=1)
    !~    call prepare(lib_tri(2),key=2,connec=[2,4,3],matkey=1)
    !~    call prepare(lib_quad(1),key=3,connec=[3,4,6,5],matkey=1)
    
        !~call prepare(lib_wedge(1),key=1,connec=[1,2,3,7,8,9],matkey=2)
        !~call prepare(lib_wedge(2),key=2,connec=[2,4,3,8,10,9],matkey=2)
        !~
        !~call prepare(lib_brick(1),key=1,connec=[3,4,6,5,9,10,12,11],matkey=2,theta=90._dp)
    
    end subroutine initialize_lib_elem
      
    
    end module lib_elem_module