    !***************************************!
    !   the global library of edges         !
    !   used in the analysis;               !
    !                                       !
    !   this module is generated by the     !
    !   preprocessing programme             !
    !***************************************!
    
    
    module lib_edge_module
    use parameter_module
    
    
    implicit none
    save
    
    integer :: lib_edge(14)
    
    
    
    
    contains
    
    
    subroutine initialize_lib_edge()
    
        integer :: i=0
        
        lib_edge=0
    
    end subroutine initialize_lib_edge
    
    end module lib_edge_module