    subroutine initialize_lib_node()          
                                              
        integer :: nnode=0                    
        integer :: i=0                        
        nnode=48   
        allocate(lib_node(nnode))   
        call update(lib_node(1),x=[-1.0_dp,-1.0_dp,-0.25_dp],u=[zero,zero,zero])
        call update(lib_node(2),x=[1.0_dp,-1.0_dp,-0.25_dp],u=[zero,zero,zero])
        call update(lib_node(3),x=[-1.0_dp,1.0_dp,-0.25_dp],u=[zero,zero,zero])
        call update(lib_node(4),x=[1.0_dp,1.0_dp,-0.25_dp],u=[zero,zero,zero])
        call update(lib_node(5),x=[-1.0_dp,-1.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(6),x=[1.0_dp,-1.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(7),x=[-1.0_dp,1.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(8),x=[1.0_dp,1.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(9),x=[-1.0_dp,-1.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(10),x=[1.0_dp,-1.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(11),x=[-1.0_dp,1.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(12),x=[1.0_dp,1.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(13),x=[-1.0_dp,-1.0_dp,0.25_dp],u=[zero,zero,zero])
        call update(lib_node(14),x=[1.0_dp,-1.0_dp,0.25_dp],u=[zero,zero,zero])
        call update(lib_node(15),x=[-1.0_dp,1.0_dp,0.25_dp],u=[zero,zero,zero])
        call update(lib_node(16),x=[1.0_dp,1.0_dp,0.25_dp],u=[zero,zero,zero])
        call update(lib_node(17),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(18),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(19),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(20),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(21),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(22),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(23),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(24),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(25),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(26),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(27),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(28),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(29),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(30),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(31),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(32),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(33),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(34),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(35),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(36),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(37),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(38),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(39),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(40),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(41),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(42),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(43),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(44),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(45),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(46),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(47),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
        call update(lib_node(48),x=[0.0_dp,0.0_dp,0.0_dp],u=[zero,zero,zero])
    end subroutine initialize_lib_node        
