    !***************************************!
    !   the global library of materials     !
    !   needed for the analysis;            !
    !                                       !
    !   this module is generated by the     !
    !   preprocessing programme             !
    !***************************************!
 
    include 'material_module.f90'
   
    module lib_mat_module
    use parameter_module
    use material_module
    
    implicit none
    save
    
    type(material)          :: lib_mat(1)
    type(isotropic_type)    :: lib_iso(1)
    type(lamina_type)       :: lib_lamina(1)
    
    contains
    
    subroutine initialize_lib_mat()
        
        integer :: i=0
        character(len=matnamelength) :: mname
        character(len=mattypelength) :: mtype
        
        mname='test1'
        mtype='isotropic'
    
        do i=1, size(lib_mat)
            call empty(lib_mat(i))
        end do
        
        do i=1, size(lib_iso)
            call empty(lib_iso(i))
        end do
        
        call update(lib_mat(1),matname=mname,mattype=mtype,matkey=1)
        call update(lib_iso(1), isotropic_modulus(E=100.0_dp, nu=0.3_dp))
    
    
    end subroutine initialize_lib_mat
    
    
    end module lib_mat_module