    !***************************************!
    !   the global library of materials     !
    !   needed for the analysis;            !
    !                                       !
    !   this module is generated by the     !
    !   preprocessing programme             !
    !***************************************!
 
    include 'material_module.f90'
   
    module lib_mat_module
    use parameter_module
    use material_module
    
    implicit none
    save
    
    type(material), allocatable          :: lib_mat(:)
    type(isotropic_type), allocatable    :: lib_iso(:)
    type(lamina_type), allocatable       :: lib_lamina(:)
    
    contains
    
    subroutine initialize_lib_mat()
        
        integer :: i=0, nmat=0, niso=0, nlamina=0
        character(len=matnamelength) :: mname
        character(len=mattypelength) :: mtype
        
        mname='test1'
        mtype='isotropic'
        nmat=1
        niso=1
        
        allocate(lib_mat(nmat))
        allocate(lib_iso(niso))
    
        do i=1, nmat
            call empty(lib_mat(i))
        end do
        
        do i=1, niso
            call empty(lib_iso(i))
        end do
        
        call update(lib_mat(1),matname=mname,mattype=mtype,matkey=1)
        call update(lib_iso(1), isotropic_modulus(E=100.0_dp, nu=zero))
    
    
    end subroutine initialize_lib_mat
    
    
    end module lib_mat_module